language: cpp

compiler: gcc

dist: bionic

addons:
  apt:
    update: true
    packages:
      - libeigen3-dev

install:
  - pip install cpplint

script:
  - make
  - gcov tests/test_main.gcno
  - bash <(curl -s https://codecov.io/bash)
