name: Release

on:
  workflow_run:
    workflows: ["Build Wheels"]
    types:
      - completed
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    name: Create GitHub Release
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_ref, 'refs/tags/v') }}
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: |
            ## Changes
            <!-- You can generate release notes automatically -->
            See the commits for details.
          draft: false
          prerelease: false
          files: artifacts/*.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_pypi:
    name: Upload PyPI
    runs-on: ubuntu-latest
    environment: pypi publisher
    permissions:
      id-token: write
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_ref, 'refs/tags/v') }}
    steps:
      - uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        # To test uploads to TestPyPI, uncomment the following:
        # with:
        #   repository-url: https://test.pypi.org/legacy/
