name: Build Wheels

on:
  pull_request:  # For testing
  workflow_run:
    workflows: ["Build HomLib"]
    types:
      - completed

jobs:
  build_wheels:
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build wheels for ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: linux-intel
            os: ubuntu-latest
    env:
      POSELIB_VERSION: "v2.0.5"

    steps:
      - name: Checkout your project
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Restore PoseLib cache
        uses: actions/cache@v4
        id: cache-poselib
        with:
          path: ~/poselib-install
          key: ${{ runner.os }}-poselib-${{ env.POSELIB_VERSION }}

      - name: Fail if cache miss
        if: steps.cache-poselib.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss for PoseLib. Build cannot proceed."
          exit 1

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10"
          CIBW_ENVIRONMENT: BUILD_SHARED_LIBS="OFF"
          CIBW_BUILD: ${{ github.event_name == 'pull_request' && 'cp310-*' || ''  }}
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y eigen3-devel
            cp -r ~/poselib-install/* /usr/local/
          CIBW_ARCHS_LINUX: "native"
          CIBW_BEFORE_ALL_WINDOWS: C:\vcpkg\vcpkg --triplet x64-windows install eigen3
          CIBW_ENVIRONMENT_WINDOWS: CMAKE_TOOLCHAIN_FILE="C:\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
          CIBW_ARCHS_WINDOWS: "native"
          CIBW_BEFORE_ALL_MACOS: brew install eigen
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
          CIBW_SKIP: "*-musllinux_x86_64"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.config.name }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz
